version: '3.7'

services:

  web:
    container_name: web
    hostname: web
    image: nginx:alpine
    working_dir: /web
    volumes:
      - ./web:/web
      - ./default.conf:/etc/nginx/conf.d/default.conf

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: 'web.local -> http://web:80, admin.web.local -> http://web:80'
      STAGE: local
    volumes:
      - ./ssl-certs:/var/lib/https-portal
    depends_on:
      - web
